#!/usr/bin/with-contenv bash

# used https://github.com/linuxserver/docker-plex as a template

echo "-------------------------------------"
echo -e "Setting up app config directory based on CONFIG_DIR env: ${CONFIG_DIR}\n"

# make config folder if it does not exist
if [ ! -d "${CONFIG_DIR}" ]; then
  echo "Directory does not exist! Creating..."
  mkdir -p "${CONFIG_DIR}"
fi

# permissions
echo "chown'ing directory to ensure correct permissions."
chown -R abc:abc "${CONFIG_DIR}"
echo "Done!"
echo -e "-------------------------------------\n"
