name: Delete Untagged Packages
on:
  schedule:
    - cron: '30 1 * * 0'
  workflow_run:
    workflows: ["Publish Docker image to Dockerhub"]
    types:
      - completed
  workflow_dispatch:
jobs:
  delete-untagged:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

# maybe set up for PR close later
# https://github.com/dataaxiom/ghcr-cleanup-action?tab=readme-ov-file#delete-image-when-pull-request-is-closed
